# Notebook Aula 2 - Análise e Pré-Processamento de Dados
## Parte 2: Pré-Processamento de Dados

In [1]:
import numpy as np
from sklearn import preprocessing

### One-Hot Encoding (1-de-N)

In [11]:
cores = np.array(['azul', 'amarelo', 'vermelho', 'azul', 'vermelho', 'amarelo'])

# Transforma em Valores Inteiros
encoder = preprocessing.LabelEncoder()
encoder.fit(cores)
cores_inteiros = encoder.transform(cores)
print cores_inteiros
print ''

# Transforma em One-Hot
oneHot = preprocessing.LabelBinarizer()
oneHot.fit(cores_inteiros)
cores_onehot = oneHot.transform(cores_inteiros)

print cores_onehot

[1 0 2 1 2 0]

[[0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]]
